package com.lingtu.mapper;

import com.lingtu.entity.TabCircleRange;

public interface TabCircleRangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_circlerange
     *
     * @mbggenerated Wed Dec 21 16:45:22 CST 2016
     */
    int deleteByPrimaryKey(Integer circleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_circlerange
     *
     * @mbggenerated Wed Dec 21 16:45:22 CST 2016
     */
    int insert(TabCircleRange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_circlerange
     *
     * @mbggenerated Wed Dec 21 16:45:22 CST 2016
     */
    int insertSelective(TabCircleRange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_circlerange
     *
     * @mbggenerated Wed Dec 21 16:45:22 CST 2016
     */
    TabCircleRange selectByPrimaryKey(Integer circleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_circlerange
     *
     * @mbggenerated Wed Dec 21 16:45:22 CST 2016
     */
    int updateByPrimaryKeySelective(TabCircleRange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_circlerange
     *
     * @mbggenerated Wed Dec 21 16:45:22 CST 2016
     */
    int updateByPrimaryKey(TabCircleRange record);
}