package com.lingtu.mapper;

import com.lingtu.entity.TabField;

public interface TabFieldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_field
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int deleteByPrimaryKey(Integer fieldid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_field
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insert(TabField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_field
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insertSelective(TabField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_field
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    TabField selectByPrimaryKey(Integer fieldid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_field
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKeySelective(TabField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_field
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKey(TabField record);
}