package com.lingtu.mapper;

import com.lingtu.entity.TabNumWarning;

public interface TabNumWarningMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_numwarning
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int deleteByPrimaryKey(Integer numid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_numwarning
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insert(TabNumWarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_numwarning
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insertSelective(TabNumWarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_numwarning
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    TabNumWarning selectByPrimaryKey(Integer numid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_numwarning
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKeySelective(TabNumWarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_numwarning
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKey(TabNumWarning record);
}