package com.lingtu.mapper;

import com.lingtu.entity.TabPrivilege;

public interface TabPrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_privilege
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int deleteByPrimaryKey(Integer privilegeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_privilege
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insert(TabPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_privilege
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insertSelective(TabPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_privilege
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    TabPrivilege selectByPrimaryKey(Integer privilegeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_privilege
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKeySelective(TabPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_privilege
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKey(TabPrivilege record);
}