package com.lingtu.mapper;

import com.lingtu.entity.TabRole;

public interface TabRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_role
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int deleteByPrimaryKey(Integer roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_role
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insert(TabRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_role
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insertSelective(TabRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_role
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    TabRole selectByPrimaryKey(Integer roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_role
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKeySelective(TabRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_role
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKey(TabRole record);
}