package com.lingtu.mapper;

import com.lingtu.entity.TabRolePrivilegeKey;

public interface TabRolePrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_role_privilege
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int deleteByPrimaryKey(TabRolePrivilegeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_role_privilege
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insert(TabRolePrivilegeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_role_privilege
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insertSelective(TabRolePrivilegeKey record);
}