package com.lingtu.entity;

public class TabCircleRange {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_circlerange.CIRCLEID
     *
     * @mbggenerated Wed Dec 21 16:45:22 CST 2016
     */
    private Integer circleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_circlerange.LNG
     *
     * @mbggenerated Wed Dec 21 16:45:22 CST 2016
     */
    private Double lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_circlerange.LAT
     *
     * @mbggenerated Wed Dec 21 16:45:22 CST 2016
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_circlerange.RADIUS
     *
     * @mbggenerated Wed Dec 21 16:45:22 CST 2016
     */
    private Double radius;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_circlerange.CIRCLEID
     *
     * @return the value of tab_circlerange.CIRCLEID
     *
     * @mbggenerated Wed Dec 21 16:45:22 CST 2016
     */
    public Integer getCircleid() {
        return circleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_circlerange.CIRCLEID
     *
     * @param circleid the value for tab_circlerange.CIRCLEID
     *
     * @mbggenerated Wed Dec 21 16:45:22 CST 2016
     */
    public void setCircleid(Integer circleid) {
        this.circleid = circleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_circlerange.LNG
     *
     * @return the value of tab_circlerange.LNG
     *
     * @mbggenerated Wed Dec 21 16:45:22 CST 2016
     */
    public Double getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_circlerange.LNG
     *
     * @param lng the value for tab_circlerange.LNG
     *
     * @mbggenerated Wed Dec 21 16:45:22 CST 2016
     */
    public void setLng(Double lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_circlerange.LAT
     *
     * @return the value of tab_circlerange.LAT
     *
     * @mbggenerated Wed Dec 21 16:45:22 CST 2016
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_circlerange.LAT
     *
     * @param lat the value for tab_circlerange.LAT
     *
     * @mbggenerated Wed Dec 21 16:45:22 CST 2016
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_circlerange.RADIUS
     *
     * @return the value of tab_circlerange.RADIUS
     *
     * @mbggenerated Wed Dec 21 16:45:22 CST 2016
     */
    public Double getRadius() {
        return radius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_circlerange.RADIUS
     *
     * @param radius the value for tab_circlerange.RADIUS
     *
     * @mbggenerated Wed Dec 21 16:45:22 CST 2016
     */
    public void setRadius(Double radius) {
        this.radius = radius;
    }
}