package com.lingtu.entity;

public class TabCompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_company.COMPANYID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer companyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_company.COMPANYNAME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String companyname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_company.COMPANYID
     *
     * @return the value of tab_company.COMPANYID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_company.COMPANYID
     *
     * @param companyid the value for tab_company.COMPANYID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_company.COMPANYNAME
     *
     * @return the value of tab_company.COMPANYNAME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_company.COMPANYNAME
     *
     * @param companyname the value for tab_company.COMPANYNAME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }
}