package com.lingtu.entity;

public class TabDeviceWarning {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_device_warning.NUM
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_device_warning.DEVICEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String deviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_device_warning.CIRCLEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer circleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_device_warning.POLYGONID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer polygonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_device_warning.NUMID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer numid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_device_warning.NUM
     *
     * @return the value of tab_device_warning.NUM
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_device_warning.NUM
     *
     * @param num the value for tab_device_warning.NUM
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_device_warning.DEVICEID
     *
     * @return the value of tab_device_warning.DEVICEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_device_warning.DEVICEID
     *
     * @param deviceid the value for tab_device_warning.DEVICEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_device_warning.CIRCLEID
     *
     * @return the value of tab_device_warning.CIRCLEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getCircleid() {
        return circleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_device_warning.CIRCLEID
     *
     * @param circleid the value for tab_device_warning.CIRCLEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setCircleid(Integer circleid) {
        this.circleid = circleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_device_warning.POLYGONID
     *
     * @return the value of tab_device_warning.POLYGONID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getPolygonid() {
        return polygonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_device_warning.POLYGONID
     *
     * @param polygonid the value for tab_device_warning.POLYGONID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setPolygonid(Integer polygonid) {
        this.polygonid = polygonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_device_warning.NUMID
     *
     * @return the value of tab_device_warning.NUMID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getNumid() {
        return numid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_device_warning.NUMID
     *
     * @param numid the value for tab_device_warning.NUMID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setNumid(Integer numid) {
        this.numid = numid;
    }
}