package com.lingtu.entity;

public class TabDevelopment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_development.DEVELOPID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer developid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_development.DEVELOPMENT
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String development;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_development.PARENTID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_development.COMPANYID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer companyid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_development.DEVELOPID
     *
     * @return the value of tab_development.DEVELOPID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getDevelopid() {
        return developid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_development.DEVELOPID
     *
     * @param developid the value for tab_development.DEVELOPID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setDevelopid(Integer developid) {
        this.developid = developid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_development.DEVELOPMENT
     *
     * @return the value of tab_development.DEVELOPMENT
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getDevelopment() {
        return development;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_development.DEVELOPMENT
     *
     * @param development the value for tab_development.DEVELOPMENT
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setDevelopment(String development) {
        this.development = development;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_development.PARENTID
     *
     * @return the value of tab_development.PARENTID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_development.PARENTID
     *
     * @param parentid the value for tab_development.PARENTID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_development.COMPANYID
     *
     * @return the value of tab_development.COMPANYID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_development.COMPANYID
     *
     * @param companyid the value for tab_development.COMPANYID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }
}