package com.lingtu.entity;

import java.util.Date;

public class TabDevice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_device.DEVICEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String deviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_device.DNAME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String dname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_device.LNG
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Double lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_device.LAT
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_device.RELNG
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Double relng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_device.RELAT
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Double relat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_device.DPIC
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String dpic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_device.DINFOR
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String dinfor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_device.DTIME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Date dtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_device.DEVELOPID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer developid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_device.TYPEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer typeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_device.DEVICEID
     *
     * @return the value of tab_device.DEVICEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_device.DEVICEID
     *
     * @param deviceid the value for tab_device.DEVICEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_device.DNAME
     *
     * @return the value of tab_device.DNAME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_device.DNAME
     *
     * @param dname the value for tab_device.DNAME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setDname(String dname) {
        this.dname = dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_device.LNG
     *
     * @return the value of tab_device.LNG
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Double getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_device.LNG
     *
     * @param lng the value for tab_device.LNG
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setLng(Double lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_device.LAT
     *
     * @return the value of tab_device.LAT
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_device.LAT
     *
     * @param lat the value for tab_device.LAT
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_device.RELNG
     *
     * @return the value of tab_device.RELNG
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Double getRelng() {
        return relng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_device.RELNG
     *
     * @param relng the value for tab_device.RELNG
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setRelng(Double relng) {
        this.relng = relng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_device.RELAT
     *
     * @return the value of tab_device.RELAT
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Double getRelat() {
        return relat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_device.RELAT
     *
     * @param relat the value for tab_device.RELAT
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setRelat(Double relat) {
        this.relat = relat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_device.DPIC
     *
     * @return the value of tab_device.DPIC
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getDpic() {
        return dpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_device.DPIC
     *
     * @param dpic the value for tab_device.DPIC
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setDpic(String dpic) {
        this.dpic = dpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_device.DINFOR
     *
     * @return the value of tab_device.DINFOR
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getDinfor() {
        return dinfor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_device.DINFOR
     *
     * @param dinfor the value for tab_device.DINFOR
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setDinfor(String dinfor) {
        this.dinfor = dinfor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_device.DTIME
     *
     * @return the value of tab_device.DTIME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Date getDtime() {
        return dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_device.DTIME
     *
     * @param dtime the value for tab_device.DTIME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setDtime(Date dtime) {
        this.dtime = dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_device.DEVELOPID
     *
     * @return the value of tab_device.DEVELOPID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getDevelopid() {
        return developid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_device.DEVELOPID
     *
     * @param developid the value for tab_device.DEVELOPID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setDevelopid(Integer developid) {
        this.developid = developid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_device.TYPEID
     *
     * @return the value of tab_device.TYPEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_device.TYPEID
     *
     * @param typeid the value for tab_device.TYPEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }
}