package com.lingtu.entity;

public class TabDeviceType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_devicetype.TYPEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_devicetype.TABNAME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String tabname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_devicetype.TABBIGNAME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String tabbigname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_devicetype.TYPENAME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String typename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_devicetype.ISLNGLAT
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Byte islnglat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_devicetype.TYPEID
     *
     * @return the value of tab_devicetype.TYPEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_devicetype.TYPEID
     *
     * @param typeid the value for tab_devicetype.TYPEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_devicetype.TABNAME
     *
     * @return the value of tab_devicetype.TABNAME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getTabname() {
        return tabname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_devicetype.TABNAME
     *
     * @param tabname the value for tab_devicetype.TABNAME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setTabname(String tabname) {
        this.tabname = tabname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_devicetype.TABBIGNAME
     *
     * @return the value of tab_devicetype.TABBIGNAME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getTabbigname() {
        return tabbigname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_devicetype.TABBIGNAME
     *
     * @param tabbigname the value for tab_devicetype.TABBIGNAME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setTabbigname(String tabbigname) {
        this.tabbigname = tabbigname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_devicetype.TYPENAME
     *
     * @return the value of tab_devicetype.TYPENAME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_devicetype.TYPENAME
     *
     * @param typename the value for tab_devicetype.TYPENAME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setTypename(String typename) {
        this.typename = typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_devicetype.ISLNGLAT
     *
     * @return the value of tab_devicetype.ISLNGLAT
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Byte getIslnglat() {
        return islnglat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_devicetype.ISLNGLAT
     *
     * @param islnglat the value for tab_devicetype.ISLNGLAT
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setIslnglat(Byte islnglat) {
        this.islnglat = islnglat;
    }
}