package com.lingtu.entity;

public class TabField {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_field.FIELDID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer fieldid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_field.FIELD
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String field;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_field.FIELDTYPE
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String fieldtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_field.TYPEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_field.CHINESE
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String chinese;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_field.ISALARM
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Byte isalarm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_field.ISSHOW
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Byte isshow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_field.FIELDID
     *
     * @return the value of tab_field.FIELDID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getFieldid() {
        return fieldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_field.FIELDID
     *
     * @param fieldid the value for tab_field.FIELDID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setFieldid(Integer fieldid) {
        this.fieldid = fieldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_field.FIELD
     *
     * @return the value of tab_field.FIELD
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getField() {
        return field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_field.FIELD
     *
     * @param field the value for tab_field.FIELD
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setField(String field) {
        this.field = field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_field.FIELDTYPE
     *
     * @return the value of tab_field.FIELDTYPE
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getFieldtype() {
        return fieldtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_field.FIELDTYPE
     *
     * @param fieldtype the value for tab_field.FIELDTYPE
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setFieldtype(String fieldtype) {
        this.fieldtype = fieldtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_field.TYPEID
     *
     * @return the value of tab_field.TYPEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_field.TYPEID
     *
     * @param typeid the value for tab_field.TYPEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_field.CHINESE
     *
     * @return the value of tab_field.CHINESE
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getChinese() {
        return chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_field.CHINESE
     *
     * @param chinese the value for tab_field.CHINESE
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setChinese(String chinese) {
        this.chinese = chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_field.ISALARM
     *
     * @return the value of tab_field.ISALARM
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Byte getIsalarm() {
        return isalarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_field.ISALARM
     *
     * @param isalarm the value for tab_field.ISALARM
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setIsalarm(Byte isalarm) {
        this.isalarm = isalarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_field.ISSHOW
     *
     * @return the value of tab_field.ISSHOW
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Byte getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_field.ISSHOW
     *
     * @param isshow the value for tab_field.ISSHOW
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setIsshow(Byte isshow) {
        this.isshow = isshow;
    }
}