package com.lingtu.entity;

public class TabNumWarning {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_numwarning.NUMID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer numid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_numwarning.WARNINGNAME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String warningname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_numwarning.UPLIMIT
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Double uplimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_numwarning.DOWNLIMET
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Double downlimet;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_numwarning.NUMID
     *
     * @return the value of tab_numwarning.NUMID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getNumid() {
        return numid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_numwarning.NUMID
     *
     * @param numid the value for tab_numwarning.NUMID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setNumid(Integer numid) {
        this.numid = numid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_numwarning.WARNINGNAME
     *
     * @return the value of tab_numwarning.WARNINGNAME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getWarningname() {
        return warningname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_numwarning.WARNINGNAME
     *
     * @param warningname the value for tab_numwarning.WARNINGNAME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setWarningname(String warningname) {
        this.warningname = warningname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_numwarning.UPLIMIT
     *
     * @return the value of tab_numwarning.UPLIMIT
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Double getUplimit() {
        return uplimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_numwarning.UPLIMIT
     *
     * @param uplimit the value for tab_numwarning.UPLIMIT
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setUplimit(Double uplimit) {
        this.uplimit = uplimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_numwarning.DOWNLIMET
     *
     * @return the value of tab_numwarning.DOWNLIMET
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Double getDownlimet() {
        return downlimet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_numwarning.DOWNLIMET
     *
     * @param downlimet the value for tab_numwarning.DOWNLIMET
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setDownlimet(Double downlimet) {
        this.downlimet = downlimet;
    }
}