package com.lingtu.entity;

public class TabPrivilege {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_privilege.privilegeid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer privilegeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_privilege.privilegename
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String privilegename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_privilege.privilegeid
     *
     * @return the value of tab_privilege.privilegeid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getPrivilegeid() {
        return privilegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_privilege.privilegeid
     *
     * @param privilegeid the value for tab_privilege.privilegeid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setPrivilegeid(Integer privilegeid) {
        this.privilegeid = privilegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_privilege.privilegename
     *
     * @return the value of tab_privilege.privilegename
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getPrivilegename() {
        return privilegename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_privilege.privilegename
     *
     * @param privilegename the value for tab_privilege.privilegename
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setPrivilegename(String privilegename) {
        this.privilegename = privilegename;
    }
}