package com.lingtu.entity;

public class TabPolyRange {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_ploygonrange.POLYGONID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer polygonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_ploygonrange.POINTARR
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String pointarr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_ploygonrange.POLYGONID
     *
     * @return the value of tab_ploygonrange.POLYGONID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getPolygonid() {
        return polygonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_ploygonrange.POLYGONID
     *
     * @param polygonid the value for tab_ploygonrange.POLYGONID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setPolygonid(Integer polygonid) {
        this.polygonid = polygonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_ploygonrange.POINTARR
     *
     * @return the value of tab_ploygonrange.POINTARR
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getPointarr() {
        return pointarr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_ploygonrange.POINTARR
     *
     * @param pointarr the value for tab_ploygonrange.POINTARR
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setPointarr(String pointarr) {
        this.pointarr = pointarr;
    }
}