package com.lingtu.entity;

public class TabPath {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_path.pathid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer pathid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_path.deviceid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String deviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_path.stime
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String stime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_path.etime
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String etime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_path.pathid
     *
     * @return the value of tab_path.pathid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getPathid() {
        return pathid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_path.pathid
     *
     * @param pathid the value for tab_path.pathid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setPathid(Integer pathid) {
        this.pathid = pathid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_path.deviceid
     *
     * @return the value of tab_path.deviceid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_path.deviceid
     *
     * @param deviceid the value for tab_path.deviceid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_path.stime
     *
     * @return the value of tab_path.stime
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getStime() {
        return stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_path.stime
     *
     * @param stime the value for tab_path.stime
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setStime(String stime) {
        this.stime = stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_path.etime
     *
     * @return the value of tab_path.etime
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getEtime() {
        return etime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_path.etime
     *
     * @param etime the value for tab_path.etime
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setEtime(String etime) {
        this.etime = etime;
    }
}