package com.lingtu.entity;

public class TabRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_role.roleid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_role.rolename
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String rolename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_role.roleid
     *
     * @return the value of tab_role.roleid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_role.roleid
     *
     * @param roleid the value for tab_role.roleid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_role.rolename
     *
     * @return the value of tab_role.rolename
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_role.rolename
     *
     * @param rolename the value for tab_role.rolename
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }
}