package com.lingtu.entity;

public class TabRolePrivilegeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_role_privilege.roleid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_role_privilege.privilegeid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer privilegeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_role_privilege.roleid
     *
     * @return the value of tab_role_privilege.roleid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_role_privilege.roleid
     *
     * @param roleid the value for tab_role_privilege.roleid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_role_privilege.privilegeid
     *
     * @return the value of tab_role_privilege.privilegeid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getPrivilegeid() {
        return privilegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_role_privilege.privilegeid
     *
     * @param privilegeid the value for tab_role_privilege.privilegeid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setPrivilegeid(Integer privilegeid) {
        this.privilegeid = privilegeid;
    }
}