package com.lingtu.entity;

public class TabUserInfor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_userinfor.USERINFOID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer userinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_userinfor.USERID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_userinfor.USERPHONE
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String userphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_userinfor.USEREMAIL
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String useremail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_userinfor.USERTRUENAEM
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String usertruenaem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_userinfor.USERIDENTITY
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String useridentity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_userinfor.USERINFOID
     *
     * @return the value of tab_userinfor.USERINFOID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getUserinfoid() {
        return userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_userinfor.USERINFOID
     *
     * @param userinfoid the value for tab_userinfor.USERINFOID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setUserinfoid(Integer userinfoid) {
        this.userinfoid = userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_userinfor.USERID
     *
     * @return the value of tab_userinfor.USERID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_userinfor.USERID
     *
     * @param userid the value for tab_userinfor.USERID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_userinfor.USERPHONE
     *
     * @return the value of tab_userinfor.USERPHONE
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getUserphone() {
        return userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_userinfor.USERPHONE
     *
     * @param userphone the value for tab_userinfor.USERPHONE
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setUserphone(String userphone) {
        this.userphone = userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_userinfor.USEREMAIL
     *
     * @return the value of tab_userinfor.USEREMAIL
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getUseremail() {
        return useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_userinfor.USEREMAIL
     *
     * @param useremail the value for tab_userinfor.USEREMAIL
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setUseremail(String useremail) {
        this.useremail = useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_userinfor.USERTRUENAEM
     *
     * @return the value of tab_userinfor.USERTRUENAEM
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getUsertruenaem() {
        return usertruenaem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_userinfor.USERTRUENAEM
     *
     * @param usertruenaem the value for tab_userinfor.USERTRUENAEM
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setUsertruenaem(String usertruenaem) {
        this.usertruenaem = usertruenaem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_userinfor.USERIDENTITY
     *
     * @return the value of tab_userinfor.USERIDENTITY
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getUseridentity() {
        return useridentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_userinfor.USERIDENTITY
     *
     * @param useridentity the value for tab_userinfor.USERIDENTITY
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setUseridentity(String useridentity) {
        this.useridentity = useridentity;
    }
}