package com.lingtu.entity;

public class TabUserRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_role.userid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_role.roleid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_role.userid
     *
     * @return the value of tab_user_role.userid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_role.userid
     *
     * @param userid the value for tab_user_role.userid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_role.roleid
     *
     * @return the value of tab_user_role.roleid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_role.roleid
     *
     * @param roleid the value for tab_user_role.roleid
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}