package com.lingtu.entity;

public class TabUserDevice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_device.NUM
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_device.USERID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_device.DEVICEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String deviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_device.COMPANYID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer companyid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_device.NUM
     *
     * @return the value of tab_user_device.NUM
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_device.NUM
     *
     * @param num the value for tab_user_device.NUM
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_device.USERID
     *
     * @return the value of tab_user_device.USERID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_device.USERID
     *
     * @param userid the value for tab_user_device.USERID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_device.DEVICEID
     *
     * @return the value of tab_user_device.DEVICEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_device.DEVICEID
     *
     * @param deviceid the value for tab_user_device.DEVICEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_device.COMPANYID
     *
     * @return the value of tab_user_device.COMPANYID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_device.COMPANYID
     *
     * @param companyid the value for tab_user_device.COMPANYID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }
}