package com.lingtu.entity;

public class TabUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user.USERID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user.USERPWD
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String userpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user.USERNAME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user.USERID
     *
     * @return the value of tab_user.USERID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user.USERID
     *
     * @param userid the value for tab_user.USERID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user.USERPWD
     *
     * @return the value of tab_user.USERPWD
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getUserpwd() {
        return userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user.USERPWD
     *
     * @param userpwd the value for tab_user.USERPWD
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user.USERNAME
     *
     * @return the value of tab_user.USERNAME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user.USERNAME
     *
     * @param username the value for tab_user.USERNAME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setUsername(String username) {
        this.username = username;
    }
}