package com.lingtu.entity;

import java.util.Date;

public class TabWarningRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_warningrecord.RECORDID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer recordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_warningrecord.NUMID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer numid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_warningrecord.DEVICEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private String deviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_warningrecord.CIRCLEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer circleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_warningrecord.POLYGONID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Integer polygonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_warningrecord.RECORDTIME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Date recordtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_warningrecord.WARNINGNUM
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    private Double warningnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_warningrecord.RECORDID
     *
     * @return the value of tab_warningrecord.RECORDID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_warningrecord.RECORDID
     *
     * @param recordid the value for tab_warningrecord.RECORDID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setRecordid(Integer recordid) {
        this.recordid = recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_warningrecord.NUMID
     *
     * @return the value of tab_warningrecord.NUMID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getNumid() {
        return numid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_warningrecord.NUMID
     *
     * @param numid the value for tab_warningrecord.NUMID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setNumid(Integer numid) {
        this.numid = numid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_warningrecord.DEVICEID
     *
     * @return the value of tab_warningrecord.DEVICEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_warningrecord.DEVICEID
     *
     * @param deviceid the value for tab_warningrecord.DEVICEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_warningrecord.CIRCLEID
     *
     * @return the value of tab_warningrecord.CIRCLEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getCircleid() {
        return circleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_warningrecord.CIRCLEID
     *
     * @param circleid the value for tab_warningrecord.CIRCLEID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setCircleid(Integer circleid) {
        this.circleid = circleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_warningrecord.POLYGONID
     *
     * @return the value of tab_warningrecord.POLYGONID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Integer getPolygonid() {
        return polygonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_warningrecord.POLYGONID
     *
     * @param polygonid the value for tab_warningrecord.POLYGONID
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setPolygonid(Integer polygonid) {
        this.polygonid = polygonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_warningrecord.RECORDTIME
     *
     * @return the value of tab_warningrecord.RECORDTIME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Date getRecordtime() {
        return recordtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_warningrecord.RECORDTIME
     *
     * @param recordtime the value for tab_warningrecord.RECORDTIME
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setRecordtime(Date recordtime) {
        this.recordtime = recordtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_warningrecord.WARNINGNUM
     *
     * @return the value of tab_warningrecord.WARNINGNUM
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public Double getWarningnum() {
        return warningnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_warningrecord.WARNINGNUM
     *
     * @param warningnum the value for tab_warningrecord.WARNINGNUM
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    public void setWarningnum(Double warningnum) {
        this.warningnum = warningnum;
    }
}