package com.lingtu.entity.mapper;

import com.lingtu.entity.TabCompany;

public interface TabCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_company
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int deleteByPrimaryKey(Integer companyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_company
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insert(TabCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_company
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insertSelective(TabCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_company
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    TabCompany selectByPrimaryKey(Integer companyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_company
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKeySelective(TabCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_company
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKey(TabCompany record);
}