package com.lingtu.entity.mapper;

import com.lingtu.entity.TabDeviceWarning;

public interface TabDeviceWarningMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_device_warning
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int deleteByPrimaryKey(Integer num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_device_warning
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insert(TabDeviceWarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_device_warning
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insertSelective(TabDeviceWarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_device_warning
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    TabDeviceWarning selectByPrimaryKey(Integer num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_device_warning
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKeySelective(TabDeviceWarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_device_warning
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKey(TabDeviceWarning record);
}