package com.lingtu.entity.mapper;

import com.lingtu.entity.TabDevice;

public interface TabDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_device
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int deleteByPrimaryKey(String deviceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_device
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insert(TabDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_device
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insertSelective(TabDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_device
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    TabDevice selectByPrimaryKey(String deviceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_device
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKeySelective(TabDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_device
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKey(TabDevice record);
}