package com.lingtu.entity.mapper;

import com.lingtu.entity.TabPolyRange;

public interface TabPolyRangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_ploygonrange
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int deleteByPrimaryKey(Integer polygonid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_ploygonrange
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insert(TabPolyRange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_ploygonrange
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insertSelective(TabPolyRange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_ploygonrange
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    TabPolyRange selectByPrimaryKey(Integer polygonid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_ploygonrange
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKeySelective(TabPolyRange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_ploygonrange
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKey(TabPolyRange record);
}