package com.lingtu.entity.mapper;

import com.lingtu.entity.TabPath;

public interface TabPathMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_path
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int deleteByPrimaryKey(Integer pathid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_path
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insert(TabPath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_path
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insertSelective(TabPath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_path
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    TabPath selectByPrimaryKey(Integer pathid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_path
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKeySelective(TabPath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_path
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKey(TabPath record);
}