package com.lingtu.entity.mapper;

import com.lingtu.entity.TabUserRoleKey;

public interface TabUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_role
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int deleteByPrimaryKey(TabUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_role
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insert(TabUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_role
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insertSelective(TabUserRoleKey record);
}