package com.lingtu.entity.mapper;

import com.lingtu.entity.TabUserDevice;

public interface TabUserDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_device
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int deleteByPrimaryKey(Integer num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_device
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insert(TabUserDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_device
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insertSelective(TabUserDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_device
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    TabUserDevice selectByPrimaryKey(Integer num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_device
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKeySelective(TabUserDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_device
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKey(TabUserDevice record);
}