package com.lingtu.entity.mapper;

import com.lingtu.entity.TabWarningRecord;

public interface TabWarningRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_warningrecord
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int deleteByPrimaryKey(Integer recordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_warningrecord
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insert(TabWarningRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_warningrecord
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int insertSelective(TabWarningRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_warningrecord
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    TabWarningRecord selectByPrimaryKey(Integer recordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_warningrecord
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKeySelective(TabWarningRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_warningrecord
     *
     * @mbggenerated Wed Dec 21 16:45:23 CST 2016
     */
    int updateByPrimaryKey(TabWarningRecord record);
}